In [1]:
import torch

In [6]:
X = torch.tensor([[1, 0],
                  [1, 1],
                  [0, 0],
                  [0, 1],
                  [1, 0]], dtype=torch.int32)

In [7]:
X

tensor([[1, 0],
        [1, 1],
        [0, 0],
        [0, 1],
        [1, 0]], dtype=torch.int32)

In [11]:
K_1 = torch.tensor([[1, 1, 0],
                    [0, 1, 1]], dtype=torch.int32)

In [12]:
K_1

tensor([[1, 1, 0],
        [0, 1, 1]], dtype=torch.int32)

In [13]:
X @ K_1

tensor([[1, 1, 0],
        [1, 2, 1],
        [0, 0, 0],
        [0, 1, 1],
        [1, 1, 0]], dtype=torch.int32)

In [14]:
K_2 = torch.tensor([[1, 0, 0],
                    [0, 0, 1]], dtype=torch.int32)

In [15]:
X @ K_2

tensor([[1, 0, 0],
        [1, 0, 1],
        [0, 0, 0],
        [0, 0, 1],
        [1, 0, 0]], dtype=torch.int32)

In [16]:
64 * 128 * 5 + 128

41088